import Navbar from "../../components/Navbar";
import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/router";
import api from "../../utils/api";
import ProtectedRoute from "../../components/ProtectedRoute";
import jsPDF from "jspdf";
import "jspdf-autotable";
import {
  RiAddLine,
  RiCloseLine,
  RiDeleteBinLine,
  RiFileTextLine,
  RiArrowLeftLine,
  RiCheckLine,
  RiLoader4Line,
} from "react-icons/ri";

/* ─── Toast ───────────────────────────────────────────────── */
function Toast({ message, onDone }) {
  useEffect(() => {
    const t = setTimeout(onDone, 3200);
    return () => clearTimeout(t);
  }, [onDone]);

  return (
    <div className="toast">
      <span className="toast-icon"><RiCheckLine /></span>
      {message}
    </div>
  );
}

/* ─── PDF Generator ────────────────────────────────────────── */
function generateInvoicePDF(invoice) {
  const doc = new jsPDF();
  const { customerName, _id, date, services, totalAmount } = invoice;

  // Background accent bar
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, 210, 38, "F");

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.text("INVOICE", 14, 22);

  // Company label
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("CRM System", 196, 15, { align: "right" });
  doc.text("Generated automatically", 196, 22, { align: "right" });

  // Meta block
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To:", 14, 52);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(customerName, 14, 60);

  // Invoice details (right side)
  const formattedDate = new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text("Invoice ID:", 140, 52);
  doc.text("Date:", 140, 60);
  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "bold");
  doc.text(`#${_id?.slice(-10).toUpperCase() || "N/A"}`, 168, 52);
  doc.setFont("helvetica", "normal");
  doc.text(formattedDate, 168, 60);

  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 70, 196, 70);

  // Services table
  const tableRows = services.map((s) => [
    s.name,
    `$${parseFloat(s.amount).toFixed(2)}`,
  ]);

  doc.autoTable({
    startY: 76,
    head: [["Service", "Amount"]],
    body: tableRows,
    theme: "grid",
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 11,
      cellPadding: 8,
    },
    bodyStyles: {
      fontSize: 10,
      cellPadding: 7,
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { cellWidth: 40, halign: "right" },
    },
    margin: { left: 14, right: 14 },
  });

  const finalY = doc.lastAutoTable.finalY || 140;

  // Total row
  doc.setFillColor(241, 245, 249);
  doc.rect(14, finalY + 4, 182, 16, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Total Amount", 20, finalY + 15);
  doc.text(`$${parseFloat(totalAmount).toFixed(2)}`, 192, finalY + 15, {
    align: "right",
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, pageHeight - 24, 196, pageHeight - 24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text("Generated by CRM System", 105, pageHeight - 14, {
    align: "center",
  });

  doc.save(`invoice-${_id?.slice(-8) || "download"}.pdf`);
}

/* ─── Page ─────────────────────────────────────────────────── */
function GenerateInvoicePage() {
  const router = useRouter();

  const [customers, setCustomers] = useState([]);
  const [customersLoading, setCustomersLoading] = useState(true);
  const [selectedCustomerId, setSelectedCustomerId] = useState("");
  const [services, setServices] = useState([{ name: "", amount: "" }]);
  const [submitting, setSubmitting] = useState(false);
  const [toast, setToast] = useState(null);
  const [errors, setErrors] = useState({});
  const toastKey = useRef(0);

  useEffect(() => {
    api.get("/customers").then(({ data }) => {
      setCustomers(data.customers || []);
    }).catch(() => { }).finally(() => setCustomersLoading(false));
  }, []);

  const selectedCustomer = customers.find((c) => c._id === selectedCustomerId);

  const totalAmount = services.reduce(
    (sum, s) => sum + (parseFloat(s.amount) || 0),
    0
  );

  const addService = () => {
    setServices((prev) => [...prev, { name: "", amount: "" }]);
  };

  const removeService = (idx) => {
    if (services.length === 1) return;
    setServices((prev) => prev.filter((_, i) => i !== idx));
  };

  const updateService = (idx, field, value) => {
    setServices((prev) =>
      prev.map((s, i) => (i === idx ? { ...s, [field]: value } : s))
    );
    setErrors((prev) => ({ ...prev, [`service_${idx}_${field}`]: undefined }));
  };

  const validate = () => {
    const errs = {};
    if (!selectedCustomerId) errs.customer = "Please select a customer.";
    services.forEach((s, i) => {
      if (!s.name.trim()) errs[`service_${i}_name`] = "Required";
      if (!s.amount || isNaN(parseFloat(s.amount)) || parseFloat(s.amount) <= 0)
        errs[`service_${i}_amount`] = "Enter a valid amount";
    });
    return errs;
  };

  const handleSubmit = async () => {
    const errs = validate();
    if (Object.keys(errs).length > 0) {
      setErrors(errs);
      return;
    }

    setSubmitting(true);
    try {
      const payload = {
        customerId: selectedCustomerId,
        customerName: selectedCustomer.name,
        services: services.map((s) => ({
          name: s.name.trim(),
          amount: parseFloat(s.amount),
        })),
      };

      const { data } = await api.post("/invoices", payload);
      const invoice = data.invoice;

      // Client-side PDF
      generateInvoicePDF(invoice);

      // Toast
      toastKey.current += 1;
      setToast({ key: toastKey.current, message: "Invoice created & PDF downloaded!" });

      // Reset form
      setSelectedCustomerId("");
      setServices([{ name: "", amount: "" }]);
      setErrors({});
    } catch (err) {
      alert(err?.response?.data?.message || "Failed to create invoice. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <>
      <Navbar />
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Sora:wght@400;500;600;700&family=DM+Sans:wght@400;500&display=swap');

        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

        .gen-page {
          min-height: calc(100vh - 64px);
          background: #f8fafc;
          padding: 36px 24px 60px;
          font-family: 'DM Sans', sans-serif;
        }

        .gen-container {
          max-width: 720px;
          margin: 0 auto;
        }

        /* Back link */
        .gen-back {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          color: #64748b;
          font-size: 13.5px;
          font-weight: 500;
          text-decoration: none;
          margin-bottom: 24px;
          transition: color 0.15s;
        }
        .gen-back:hover { color: #6366f1; }
        .gen-back svg { font-size: 16px; }

        /* Header */
        .gen-header {
          margin-bottom: 28px;
        }
        .gen-header h1 {
          font-family: 'Sora', sans-serif;
          font-size: 24px;
          font-weight: 700;
          color: #0f172a;
          letter-spacing: -0.4px;
        }
        .gen-header p {
          font-size: 14px;
          color: #64748b;
          margin-top: 4px;
        }

        /* Card */
        .gen-card {
          background: #fff;
          border-radius: 18px;
          border: 1px solid #e8edf5;
          box-shadow: 0 2px 16px rgba(0,0,0,0.05);
          overflow: hidden;
          margin-bottom: 20px;
        }

        .gen-card-header {
          padding: 18px 24px 16px;
          border-bottom: 1px solid #f1f5f9;
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .gen-card-header-icon {
          width: 34px;
          height: 34px;
          border-radius: 9px;
          background: rgba(99,102,241,0.1);
          color: #6366f1;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 17px;
        }

        .gen-card-header h2 {
          font-family: 'Sora', sans-serif;
          font-size: 15px;
          font-weight: 600;
          color: #0f172a;
        }

        .gen-card-body {
          padding: 24px;
        }

        /* Form fields */
        .field-group {
          margin-bottom: 20px;
        }

        .field-label {
          display: block;
          font-size: 13px;
          font-weight: 600;
          color: #374151;
          margin-bottom: 7px;
          letter-spacing: 0.1px;
        }

        .field-select,
        .field-input {
          width: 100%;
          padding: 10px 14px;
          background: #fff;
          border: 1.5px solid #e2e8f0;
          border-radius: 10px;
          font-size: 14px;
          font-family: 'DM Sans', sans-serif;
          color: #1e293b;
          outline: none;
          transition: border-color 0.15s, box-shadow 0.15s;
          appearance: none;
        }

        .field-select:focus,
        .field-input:focus {
          border-color: #6366f1;
          box-shadow: 0 0 0 3px rgba(99,102,241,0.1);
        }

        .field-select.error,
        .field-input.error {
          border-color: #f87171;
          box-shadow: 0 0 0 3px rgba(248,113,113,0.1);
        }

        .field-error {
          font-size: 12px;
          color: #ef4444;
          margin-top: 5px;
        }

        /* Services */
        .services-list {
          display: flex;
          flex-direction: column;
          gap: 12px;
          margin-bottom: 16px;
        }

        .service-row {
          display: grid;
          grid-template-columns: 1fr 140px 40px;
          gap: 10px;
          align-items: start;
          padding: 14px;
          background: #f8fafc;
          border: 1px solid #e8edf5;
          border-radius: 12px;
          transition: border-color 0.15s;
        }

        .service-row:focus-within {
          border-color: #c7d2fe;
          background: #fafbff;
        }

        .service-field { display: flex; flex-direction: column; gap: 4px; }
        .service-field-label {
          font-size: 11px;
          font-weight: 600;
          color: #94a3b8;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }

        .remove-btn {
          width: 36px;
          height: 36px;
          background: transparent;
          border: 1.5px solid #e2e8f0;
          border-radius: 8px;
          color: #94a3b8;
          display: flex;
          align-items: center;
          justify-content: center;
          cursor: pointer;
          transition: all 0.15s;
          font-size: 16px;
          flex-shrink: 0;
          align-self: center;
          margin-top: 16px;
        }
        .remove-btn:hover:not(:disabled) {
          background: #fef2f2;
          border-color: #fecaca;
          color: #ef4444;
        }
        .remove-btn:disabled { opacity: 0.3; cursor: not-allowed; }

        .add-service-btn {
          display: inline-flex;
          align-items: center;
          gap: 7px;
          padding: 9px 18px;
          background: transparent;
          border: 1.5px dashed #c7d2fe;
          border-radius: 10px;
          color: #6366f1;
          font-size: 13.5px;
          font-weight: 600;
          font-family: 'DM Sans', sans-serif;
          cursor: pointer;
          transition: all 0.15s;
          width: 100%;
          justify-content: center;
        }
        .add-service-btn:hover {
          background: rgba(99,102,241,0.05);
          border-color: #818cf8;
        }

        /* Total */
        .total-box {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 16px 20px;
          background: linear-gradient(135deg, #eef2ff 0%, #f5f3ff 100%);
          border-radius: 12px;
          border: 1px solid #c7d2fe;
          margin-top: 20px;
        }

        .total-label {
          font-size: 13px;
          font-weight: 600;
          color: #6366f1;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }

        .total-amount {
          font-family: 'Sora', sans-serif;
          font-size: 22px;
          font-weight: 700;
          color: #4f46e5;
        }

        /* Submit */
        .gen-submit-btn {
          width: 100%;
          padding: 13px 24px;
          background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
          color: #fff;
          border: none;
          border-radius: 12px;
          font-size: 15px;
          font-weight: 600;
          font-family: 'DM Sans', sans-serif;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
          box-shadow: 0 4px 14px rgba(99,102,241,0.35);
          transition: all 0.2s ease;
        }
        .gen-submit-btn:hover:not(:disabled) {
          transform: translateY(-1px);
          box-shadow: 0 6px 20px rgba(99,102,241,0.45);
        }
        .gen-submit-btn:disabled {
          opacity: 0.65;
          cursor: not-allowed;
          transform: none;
        }

        .spin {
          animation: spin 0.8s linear infinite;
          display: inline-flex;
        }
        @keyframes spin { to { transform: rotate(360deg); } }

        /* Toast */
        .toast {
          position: fixed;
          bottom: 28px;
          right: 28px;
          background: #0f172a;
          color: #fff;
          padding: 14px 20px;
          border-radius: 12px;
          font-size: 14px;
          font-weight: 500;
          font-family: 'DM Sans', sans-serif;
          display: flex;
          align-items: center;
          gap: 10px;
          box-shadow: 0 8px 30px rgba(0,0,0,0.25);
          z-index: 9999;
          animation: slideUp 0.3s ease;
        }

        .toast-icon {
          width: 26px;
          height: 26px;
          border-radius: 50%;
          background: #10b981;
          color: #fff;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 14px;
          flex-shrink: 0;
        }

        @keyframes slideUp {
          from { transform: translateY(16px); opacity: 0; }
          to   { transform: translateY(0);    opacity: 1; }
        }

        @media (max-width: 580px) {
          .service-row { grid-template-columns: 1fr 100px 36px; }
        }
      `}</style>

      <div className="gen-page">
        
        <div className="gen-container">

          <a href="/invoices" className="gen-back">
            <RiArrowLeftLine />
            Back to Invoices
          </a>

          <div className="gen-header">
            <h1>Generate Invoice</h1>
            <p>Fill in the details below to create and download a new invoice</p>
          </div>

          {/* Customer Select */}
          <div className="gen-card">
            <div className="gen-card-header">
              <div className="gen-card-header-icon"><RiFileTextLine /></div>
              <h2>Customer Details</h2>
            </div>
            <div className="gen-card-body">
              <div className="field-group">
                <label className="field-label">Select Customer *</label>
                <select
                  className={`field-select ${errors.customer ? "error" : ""}`}
                  value={selectedCustomerId}
                  onChange={(e) => {
                    setSelectedCustomerId(e.target.value);
                    setErrors((prev) => ({ ...prev, customer: undefined }));
                  }}
                  disabled={customersLoading}
                >
                  <option value="">
                    {customersLoading ? "Loading customers…" : "— Select a customer —"}
                  </option>
                  {customers.map((c) => (
                    <option key={c._id} value={c._id}>
                      {c.name}{c.email ? ` (${c.email})` : ""}
                    </option>
                  ))}
                </select>
                {errors.customer && (
                  <div className="field-error">{errors.customer}</div>
                )}
              </div>
            </div>
          </div>

          {/* Services */}
          <div className="gen-card">
            <div className="gen-card-header">
              <div className="gen-card-header-icon"><RiAddLine /></div>
              <h2>Services</h2>
            </div>
            <div className="gen-card-body">
              <div className="services-list">
                {services.map((svc, idx) => (
                  <div key={idx} className="service-row">
                    <div className="service-field">
                      <span className="service-field-label">Service Name</span>
                      <input
                        className={`field-input ${errors[`service_${idx}_name`] ? "error" : ""}`}
                        placeholder="e.g. Web Design"
                        value={svc.name}
                        onChange={(e) => updateService(idx, "name", e.target.value)}
                      />
                      {errors[`service_${idx}_name`] && (
                        <div className="field-error">{errors[`service_${idx}_name`]}</div>
                      )}
                    </div>
                    <div className="service-field">
                      <span className="service-field-label">Amount ($)</span>
                      <input
                        className={`field-input ${errors[`service_${idx}_amount`] ? "error" : ""}`}
                        placeholder="0.00"
                        type="number"
                        min="0"
                        step="0.01"
                        value={svc.amount}
                        onChange={(e) => updateService(idx, "amount", e.target.value)}
                      />
                      {errors[`service_${idx}_amount`] && (
                        <div className="field-error">{errors[`service_${idx}_amount`]}</div>
                      )}
                    </div>
                    <button
                      className="remove-btn"
                      onClick={() => removeService(idx)}
                      disabled={services.length === 1}
                      title="Remove service"
                    >
                      <RiDeleteBinLine />
                    </button>
                  </div>
                ))}
              </div>

              <button className="add-service-btn" onClick={addService}>
                <RiAddLine />
                Add Service
              </button>

              <div className="total-box">
                <span className="total-label">Total Amount</span>
                <span className="total-amount">
                  ${totalAmount.toFixed(2)}
                </span>
              </div>
            </div>
          </div>

          {/* Submit */}
          <button
            className="gen-submit-btn"
            onClick={handleSubmit}
            disabled={submitting}
          >
            {submitting ? (
              <>
                <span className="spin"><RiLoader4Line /></span>
                Creating Invoice…
              </>
            ) : (
              <>
                <RiFileTextLine />
                Create & Download Invoice
              </>
            )}
          </button>
        </div>
      </div>

      {/* Toast */}
      {toast && (
        <Toast
          key={toast.key}
          message={toast.message}
          onDone={() => setToast(null)}
        />
      )}
    </>
  );
}

export default function GenerateInvoice() {
  return (
    <ProtectedRoute>
      <GenerateInvoicePage />
    </ProtectedRoute>
  );
}